import { FlashcardSet, FlashcardStatsData } from "../types";

export const MOCK_FLASHCARD_SETS: FlashcardSet[] = [
  {
    id: "ielts-core-vocab",
    slug: "ielts-core-vocab",
    name: "IELTS 7.5+ Core Academic Vocabulary",
    topic: "IELTS",
    description:
      "Tập hợp 120 từ vựng học thuật tần suất cao nhất trong bài thi IELTS Reading & Writing Task 2.",
    totalCards: 28,
    masteredPercent: 71,
    dueTodayCount: 8,
    lastStudied: "2 giờ trước",
    cards: [
      {
        id: "card-1",
        front: "comprehensive",
        ipa: "/ˌkɒm.prɪˈhen.sɪv/",
        pos: "adjective",
        definition: "Complete and including everything that is necessary.",
        translationVi: "Toàn diện, bao hàm đầy đủ",
        exampleSentence: "The government published a comprehensive review of national healthcare.",
        memoryNote: "Gốc từ: 'comprehend' (thấu hiểu) -> comprehensive = hiểu sâu rộng toàn diện.",
        status: "Review",
        lastReviewed: "Hôm qua",
        missCount: 2,
      },
      {
        id: "card-2",
        front: "substantiate",
        ipa: "/səbˈstæn.ʃi.eɪt/",
        pos: "verb",
        definition: "To provide facts or evidence to prove that something is true.",
        translationVi: "Chứng minh, xác thực",
        exampleSentence: "There is little scientific evidence to substantiate these dramatic claims.",
        memoryNote: "Tương đương prove with substance/evidence.",
        status: "Learning",
        lastReviewed: "3 ngày trước",
        missCount: 4,
      },
      {
        id: "card-3",
        front: "unprecedented",
        ipa: "/ʌnˈpres.ɪ.den.tɪd/",
        pos: "adjective",
        definition: "Never having happened or existed in the past.",
        translationVi: "Chưa từng có tiền lệ",
        exampleSentence: "The pandemic caused an unprecedented shock to the global supply chain.",
        memoryNote: "Un + precedent (tiền lệ) + ed.",
        status: "Mastered",
        lastReviewed: "5 ngày trước",
        missCount: 0,
      },
      {
        id: "card-4",
        front: "ubiquitous",
        ipa: "/juːˈbɪk.wɪ.təs/",
        pos: "adjective",
        definition: "Seeming to be everywhere at the same time.",
        translationVi: "Phổ biến ở khắp mọi nơi",
        exampleSentence: "Smartphones have become ubiquitous across all demographics.",
        memoryNote: "Đồng nghĩa với omnipresent, pervasive.",
        status: "Review",
        lastReviewed: "1 ngày trước",
        missCount: 3,
      },
      {
        id: "card-5",
        front: "mitigate",
        ipa: "/ˈmɪt.ɪ.ɡeɪt/",
        pos: "verb",
        definition: "To make something less harmful, unpleasant, or bad.",
        translationVi: "Giảm nhẹ, làm dịu bớt",
        exampleSentence: "Strict conservation laws help mitigate the environmental impact of factories.",
        memoryNote: "Mitigate risk/damage/disaster.",
        status: "Review",
        lastReviewed: "4 ngày trước",
        missCount: 1,
      },
      {
        id: "card-6",
        front: "paradigm",
        ipa: "/ˈpær.ə.daɪm/",
        pos: "noun",
        definition: "A model or very clear and typical example of something.",
        translationVi: "Mô hình, khuôn mẫu mẫu mực",
        exampleSentence: "The discovery created a new paradigm in modern quantum physics.",
        memoryNote: "Paradigm shift = sự thay đổi tư duy/mô hình căn bản.",
        status: "Learning",
        lastReviewed: "Hôm qua",
        missCount: 3,
      },
      {
        id: "card-7",
        front: "lucrative",
        ipa: "/ˈluː.krə.tɪv/",
        pos: "adjective",
        definition: "Producing a large amount of money or making a large profit.",
        translationVi: "Béo bở, sinh lợi cao",
        exampleSentence: "E-commerce proved to be an extremely lucrative business model during lock-downs.",
        memoryNote: "Lucrative market/contract/deal.",
        status: "Mastered",
        lastReviewed: "1 tuần trước",
        missCount: 0,
      },
      {
        id: "card-8",
        front: "pragmatic",
        ipa: "/præɡˈmæt.ɪk/",
        pos: "adjective",
        definition: "Solving problems in a sensible way that suits conditions rather than following fixed rules.",
        translationVi: "Thực tế, thực dụng",
        exampleSentence: "We need a pragmatic approach to renewable energy transition.",
        memoryNote: "Trái nghĩa với idealistic (duy tâm/lý thuyết suông).",
        status: "New",
        lastReviewed: "Chưa học",
        missCount: 1,
      },
    ],
  },
  {
    id: "toeic-office-collocations",
    slug: "toeic-office-collocations",
    name: "TOEIC 850+ Office & Business Collocations",
    topic: "TOEIC",
    description:
      "Các cụm từ cố định trong thư từ văn phòng, hợp đồng kinh doanh và đàm phán thương mại.",
    totalCards: 24,
    masteredPercent: 54,
    dueTodayCount: 6,
    lastStudied: "1 ngày trước",
    cards: [
      {
        id: "toeic-1",
        front: "come to an agreement",
        ipa: "/kʌm tuː ən əˈɡriː.mənt/",
        pos: "idiom / collocation",
        definition: "To reach a mutual understanding or settlement after negotiation.",
        translationVi: "Đạt được thỏa thuận chung",
        exampleSentence: "Both corporations finally came to an agreement on patent licenses.",
        memoryNote: "Reach an agreement = come to terms.",
        status: "Review",
        lastReviewed: "1 ngày trước",
        missCount: 1,
      },
      {
        id: "toeic-2",
        front: "in compliance with",
        ipa: "/ɪn kəmˈplaɪ.əns wɪð/",
        pos: "prepositional phrase",
        definition: "In accordance with a rule, regulation, or legal demand.",
        translationVi: "Tuân thủ theo đúng quy định",
        exampleSentence: "All production stages must strictly operate in compliance with ISO standards.",
        memoryNote: "Comply with -> in compliance with.",
        status: "Learning",
        lastReviewed: "2 ngày trước",
        missCount: 2,
      },
      {
        id: "toeic-3",
        front: "contingency plan",
        ipa: "/kənˈtɪn.dʒən.si plæn/",
        pos: "noun phrase",
        definition: "A plan designed to take account of a possible future event or circumstance.",
        translationVi: "Kế hoạch dự phòng (khi có sự cố)",
        exampleSentence: "Our finance department prepared a contingency plan in case of currency fluctuation.",
        memoryNote: "Plan B = contingency plan.",
        status: "Mastered",
        lastReviewed: "3 ngày trước",
        missCount: 0,
      },
      {
        id: "toeic-4",
        front: "expedite",
        ipa: "/ˈek.spə.daɪt/",
        pos: "verb",
        definition: "To cause something to happen faster or be done more quickly.",
        translationVi: "Xúc tiến, đẩy nhanh tiến độ",
        exampleSentence: "Please pay the express handling fee to expedite shipping.",
        memoryNote: "Expedite delivery/shipping/process.",
        status: "Review",
        lastReviewed: "1 ngày trước",
        missCount: 2,
      },
    ],
  },
  {
    id: "daily-conversational-idioms",
    slug: "daily-conversational-idioms",
    name: "Daily Conversational Idioms & Slang",
    topic: "Daily Conversation",
    description:
      "Các thành ngữ giao tiếp tiếng Anh đời sống phổ biến tại Mỹ và Anh, giúp nói tự nhiên như người bản xứ.",
    totalCards: 20,
    masteredPercent: 80,
    dueTodayCount: 4,
    lastStudied: "Hôm qua",
    cards: [
      {
        id: "idiom-1",
        front: "bite the bullet",
        ipa: "/baɪt ðə ˈbʊl.ɪt/",
        pos: "idiom",
        definition: "To force yourself to do something unpleasant or difficult.",
        translationVi: "Cắn răng chấp nhận / dũng cảm làm việc khó",
        exampleSentence: "I finally bit the bullet and decided to quit my boring 9-to-5 job.",
        memoryNote: "Nguồn gốc: thương binh cắn đạn chì khi mổ cứu thương thời chiến.",
        status: "Mastered",
        lastReviewed: "Hôm qua",
        missCount: 0,
      },
      {
        id: "idiom-2",
        front: "hit the nail on the head",
        ipa: "/hɪt ðə neɪl ɒn ðə hed/",
        pos: "idiom",
        definition: "To describe exactly what is causing a situation or problem.",
        translationVi: "Nói trúng phóc, chỉ ra chính xác vấn đề",
        exampleSentence: "You hit the nail on the head when you mentioned user experience as our core flaw.",
        memoryNote: "Đóng đinh trúng đầu đinh.",
        status: "Review",
        lastReviewed: "2 ngày trước",
        missCount: 1,
      },
      {
        id: "idiom-3",
        front: "on the fence",
        ipa: "/ɒn ðə fens/",
        pos: "idiom",
        definition: "Not able to decide something, undecided.",
        translationVi: "Lưỡng lự, chưa quyết định được bên nào",
        exampleSentence: "Many voters are still on the fence about which candidate to support.",
        memoryNote: "Ngồi trên hàng rào chưa nghiêng sang bên nào.",
        status: "Review",
        lastReviewed: "Hôm qua",
        missCount: 2,
      },
    ],
  },
  {
    id: "travel-essentials",
    slug: "travel-essentials",
    name: "Travel & Airport Essential Expressions",
    topic: "Travel",
    description:
      "Tự tin check-in sân bay, hỏi đường, đặt bàn khách sạn và xử lý các tình huống du lịch nước ngoài.",
    totalCards: 18,
    masteredPercent: 45,
    dueTodayCount: 6,
    lastStudied: "3 ngày trước",
    cards: [
      {
        id: "travel-1",
        front: "layover",
        ipa: "/ˈleɪˌoʊ.vɚ/",
        pos: "noun",
        definition: "A short stay in a place that you make while you are on a longer journey to somewhere else.",
        translationVi: "Thời gian quá cảnh / chờ nối chuyến",
        exampleSentence: "We have a 4-hour layover at Incheon International Airport before flying to Los Angeles.",
        memoryNote: "Stopover (nghỉ dài hơn 24h) vs layover (dưới 24h).",
        status: "Learning",
        lastReviewed: "3 ngày trước",
        missCount: 1,
      },
      {
        id: "travel-2",
        front: "baggage carousel",
        ipa: "/ˈbæɡ.ɪdʒ kəˌruːˈsel/",
        pos: "noun phrase",
        definition: "A continuous moving belt from which passengers pick up their luggage at an airport.",
        translationVi: "Băng chuyền hành lý sân bay",
        exampleSentence: "Our flight bags should arrive at carousel number 4 shortly.",
        memoryNote: "Băng chuyền quay vòng như vòng xoay ngựa gỗ (carousel).",
        status: "New",
        lastReviewed: "Chưa học",
        missCount: 0,
      },
    ],
  },
];

export const MOCK_FLASHCARD_STATS: FlashcardStatsData = {
  period: "7 Days",
  totalCardsLearned: 342,
  retentionRatePercent: 88,
  studyTimeHours: 12.5,
  dailyStreakDays: 14,
  activityDays: [
    { day: "T2", cardsCount: 35 },
    { day: "T3", cardsCount: 48 },
    { day: "T4", cardsCount: 42 },
    { day: "T5", cardsCount: 60 },
    { day: "T6", cardsCount: 52 },
    { day: "T7", cardsCount: 75 },
    { day: "CN", cardsCount: 30 },
  ],
  difficultCards: [
    {
      id: "card-2",
      card: "substantiate",
      set: "IELTS 7.5+ Core Academic Vocabulary",
      missCount: 4,
      lastReview: "3 ngày trước",
    },
    {
      id: "card-6",
      card: "paradigm",
      set: "IELTS 7.5+ Core Academic Vocabulary",
      missCount: 3,
      lastReview: "Hôm qua",
    },
    {
      id: "card-4",
      card: "ubiquitous",
      set: "IELTS 7.5+ Core Academic Vocabulary",
      missCount: 3,
      lastReview: "1 ngày trước",
    },
    {
      id: "toeic-2",
      card: "in compliance with",
      set: "TOEIC 850+ Office & Business Collocations",
      missCount: 2,
      lastReview: "2 ngày trước",
    },
  ],
  history: [
    {
      id: "hist-1",
      date: "08/09/2026 - 08:30",
      set: "IELTS 7.5+ Core Academic Vocabulary",
      cardsCount: 20,
      recallPercent: 85,
      studyTime: "14 phút",
    },
    {
      id: "hist-2",
      date: "07/09/2026 - 21:15",
      set: "Daily Conversational Idioms & Slang",
      cardsCount: 15,
      recallPercent: 93,
      studyTime: "9 phút",
    },
    {
      id: "hist-3",
      date: "06/09/2026 - 19:40",
      set: "TOEIC 850+ Office & Business Collocations",
      cardsCount: 24,
      recallPercent: 79,
      studyTime: "18 phút",
    },
    {
      id: "hist-4",
      date: "05/09/2026 - 07:50",
      set: "IELTS 7.5+ Core Academic Vocabulary",
      cardsCount: 18,
      recallPercent: 88,
      studyTime: "12 phút",
    },
  ],
};
