import { IpaChartSound, PronunciationLesson } from "../types";

export const MOCK_PRONUNCIATION_LESSONS: PronunciationLesson[] = [
  {
    id: "minimal-pair-i-long-short",
    slug: "minimal-pair-i-long-short",
    title: "Cặp âm kinh điển: /iː/ (dài) vs /ɪ/ (ngắn)",
    category: "Minimal Pairs",
    level: "Beginner",
    phonemeTarget: "/iː/ vs /ɪ/",
    targetSentence: "Please sit on this seat and leave your sheet on the ship.",
    ipaTranscript: "/pliːz sɪt ɒn ðɪs siːt ænd liːv jɔː ʃiːt ɒn ðə ʃɪp/",
    translationVi: "Xin vui lòng ngồi vào chiếc ghế này và để lại tờ giấy của bạn trên con tàu.",
    phonemes: [
      { symbol: "/iː/", soundType: "vowel", isKeyTarget: true },
      { symbol: "/ɪ/", soundType: "vowel", isKeyTarget: true },
      { symbol: "/s/", soundType: "consonant" },
      { symbol: "/ʃ/", soundType: "consonant" },
    ],
    tips: [
      "Âm /iː/: Kéo khóe miệng sang hai bên như đang cười nhẹ, giữ luồng hơi dài và căng cơ môi.",
      "Âm /ɪ/: Thả lỏng cơ miệng, phát âm dứt khoát nửa giống 'i' nửa giống 'ê' trong tiếng Việt.",
    ],
    bestScore: 88,
  },
  {
    id: "th-sound-voiced-unvoiced",
    slug: "th-sound-voiced-unvoiced",
    title: "Âm kẹp lưỡi: /θ/ (không rung) vs /ð/ (có rung)",
    category: "Minimal Pairs",
    level: "Intermediate",
    phonemeTarget: "/θ/ vs /ð/",
    targetSentence: "I thought thirty-three thousand people breathed through the cold weather.",
    ipaTranscript: "/aɪ θɔːt ˈθɜː.ti θriː ˈθaʊ.zənd ˈpiː.pəl briːðd θruː ðə kəʊld ˈweð.ər/",
    translationVi: "Tôi nghĩ ba mươi ba nghìn người đã hít thở qua tiết trời giá lạnh.",
    phonemes: [
      { symbol: "/θ/", soundType: "consonant", isKeyTarget: true },
      { symbol: "/ð/", soundType: "consonant", isKeyTarget: true },
      { symbol: "/z/", soundType: "consonant" },
    ],
    tips: [
      "Đặt đầu lưỡi nhẹ nhàng giữa hai hàm răng trên và dưới, đẩy luồng hơi êm ra ngoài.",
      "Với âm /ð/: Đặt ngón tay lên cổ họng để cảm nhận độ rung rõ rệt của dây thanh quản.",
    ],
    bestScore: 78,
  },
  {
    id: "ielts-speaking-academic-fluency",
    slug: "ielts-speaking-academic-fluency",
    title: "IELTS Speaking 8.0+: Nối âm & Nhịp điệu học thuật",
    category: "IELTS Speaking",
    level: "Advanced",
    phonemeTarget: "Linking Sounds & Rhythm",
    targetSentence: "The exponential growth of artificial intelligence has revolutionized sustainable energy.",
    ipaTranscript: "/ði ˌek.spəˈnen.ʃəl ɡrəʊθ əv ˌɑː.tɪˈfɪʃ.əl ɪnˈtel.ɪ.dʒəns hæz ˌrev.əˈluː.ʃən.aɪzd səˈsteɪ.nə.bəl ˈen.ə.dʒi/",
    translationVi: "Sự phát triển theo cấp số nhân của trí tuệ nhân tạo đã cách mạng hóa ngành năng lượng bền vững.",
    phonemes: [
      { symbol: "/ʃ/", soundType: "consonant" },
      { symbol: "/dʒ/", soundType: "consonant" },
      { symbol: "/z/", soundType: "consonant" },
      { symbol: "/ə/", soundType: "vowel" },
    ],
    tips: [
      "Chú ý trọng âm chính của từ 'ex-po-NEN-tial' và 're-vo-LU-tion-ized'.",
      "Nối âm nhẹ nhàng giữa 'growth of' -> /ɡrəʊθ‿əv/ để tạo độ mượt tự nhiên.",
    ],
    bestScore: 92,
  },
  {
    id: "daily-conversational-intonation",
    slug: "daily-conversational-intonation",
    title: "Giao tiếp đời thường: Lên giọng ở câu hỏi & Nuốt âm",
    category: "Daily Conversations",
    level: "Beginner",
    phonemeTarget: "Rising Intonation",
    targetSentence: "Could you please give me a hand with this heavy baggage?",
    ipaTranscript: "/kʊd juː pliːz ɡɪv miː ə hænd wɪð ðɪs ˈhev.i ˈbæɡ.ɪdʒ/",
    translationVi: "Bạn có thể vui lòng giúp tôi một tay với chỗ hành lý nặng này được không?",
    phonemes: [
      { symbol: "/ʊ/", soundType: "vowel" },
      { symbol: "/æ/", soundType: "vowel" },
      { symbol: "/dʒ/", soundType: "consonant" },
    ],
    tips: [
      "Câu hỏi Yes/No cần nâng cao tông giọng ở từ cuối cùng 'baggage?'.",
      "Cụm 'Could you' phát âm nối thành /ˈkʊd.ʒuː/.",
    ],
    bestScore: 85,
  },
  {
    id: "business-presentation-stress",
    slug: "business-presentation-stress",
    title: "Thuyết trình kinh doanh: Nhấn mạnh số liệu & Trọng âm câu",
    category: "Business Pitch",
    level: "Intermediate",
    phonemeTarget: "Sentence Stress",
    targetSentence: "We project a thirty percent revenue increase over the upcoming fiscal year.",
    ipaTranscript: "/wiː prəˈdʒekt ə ˈθɜː.ti pəˈsent ˈrev.ən.juː ˈɪn.kriːs ˈəʊ.vər ði ˈʌpˌkʌm.ɪŋ ˈfɪs.kəl jɪər/",
    translationVi: "Chúng tôi dự báo mức tăng doanh thu ba mươi phần trăm trong năm tài chính sắp tới.",
    phonemes: [
      { symbol: "/θ/", soundType: "consonant" },
      { symbol: "/ɪn/", soundType: "stress" },
      { symbol: "/ʌ/", soundType: "vowel" },
    ],
    tips: [
      "Nhấn mạnh các từ mang thông tin then chốt: 'THIR-ty percent', 'RE-ve-nue INCREASE', 'UP-coming'.",
      "Giảm âm các từ chức năng như 'a', 'the', 'over'.",
    ],
  },
];

export const MOCK_IPA_CHART: IpaChartSound[] = [
  // Monophthongs
  { symbol: "/iː/", example: "see, eat", type: "monophthong", isMastered: true },
  { symbol: "/ɪ/", example: "sit, bit", type: "monophthong", isMastered: true },
  { symbol: "/e/", example: "bed, red", type: "monophthong", isMastered: true },
  { symbol: "/æ/", example: "cat, bad", type: "monophthong", isMastered: false },
  { symbol: "/ʌ/", example: "cup, but", type: "monophthong", isMastered: true },
  { symbol: "/ɑː/", example: "father, car", type: "monophthong", isMastered: false },
  { symbol: "/ɒ/", example: "hot, pot", type: "monophthong", isMastered: true },
  { symbol: "/ɔː/", example: "call, four", type: "monophthong", isMastered: false },
  { symbol: "/ʊ/", example: "put, foot", type: "monophthong", isMastered: true },
  { symbol: "/uː/", example: "too, food", type: "monophthong", isMastered: true },
  { symbol: "/ɜː/", example: "bird, word", type: "monophthong", isMastered: false },
  { symbol: "/ə/", example: "about, ago", type: "monophthong", isMastered: true },

  // Consonants
  { symbol: "/θ/", example: "think, bath", type: "consonant", isMastered: false },
  { symbol: "/ð/", example: "this, mother", type: "consonant", isMastered: false },
  { symbol: "/ʃ/", example: "she, cash", type: "consonant", isMastered: true },
  { symbol: "/ʒ/", example: "measure, vision", type: "consonant", isMastered: false },
  { symbol: "/tʃ/", example: "chip, watch", type: "consonant", isMastered: true },
  { symbol: "/dʒ/", example: "jam, judge", type: "consonant", isMastered: true },
  { symbol: "/ŋ/", example: "sing, long", type: "consonant", isMastered: true },
];
