import { DailyPathNode, DailyQuest, QuizItem } from "../types";

export const MOCK_DAILY_PATH_NODES: DailyPathNode[] = [
  {
    id: "node-1",
    title: "Khởi động: Giới từ & Cụm thời gian",
    subtitle: "Nắm vững in / on / at và giới từ chỉ vị trí",
    type: "LESSON",
    status: "COMPLETED",
    order: 1,
    xpReward: 50,
    starsEarned: 3,
  },
  {
    id: "node-2",
    title: "Mini Quiz: Trắc nghiệm giới từ",
    subtitle: "10 câu hỏi kiểm tra phản xạ nhanh",
    type: "QUIZ",
    status: "COMPLETED",
    order: 2,
    xpReward: 80,
    starsEarned: 3,
    targetQuizId: "preposition-mini-quiz",
  },
  {
    id: "node-3",
    title: "Thì Hiện tại hoàn thành vs Quá khứ đơn",
    subtitle: "Phân biệt Since / For và mốc thời gian xác định",
    type: "LESSON",
    status: "COMPLETED",
    order: 3,
    xpReward: 60,
    starsEarned: 2,
  },
  {
    id: "node-4",
    title: "Thử thách: IELTS & Academic Grammar Master",
    subtitle: "Chinh phục 5 dạng câu hỏi: Trắc nghiệm, Điền từ, Viết lại câu, Sắp xếp & Nối vế",
    type: "QUIZ",
    status: "CURRENT",
    order: 4,
    xpReward: 120,
    starsEarned: 0,
    targetQuizId: "ielts-academic-grammar",
  },
  {
    id: "node-5",
    title: "Đảo ngữ & Câu điều kiện hỗn hợp",
    subtitle: "Cấu trúc nâng cao ghi điểm Band 7.0+",
    type: "LESSON",
    status: "LOCKED",
    order: 5,
    xpReward: 70,
  },
  {
    id: "node-6",
    title: "Cột mốc: Đánh giá Năng lực Tuần 2",
    subtitle: "Tổng hợp kiến thức toàn diện mở khóa huy hiệu",
    type: "MILESTONE",
    status: "LOCKED",
    order: 6,
    xpReward: 200,
    targetQuizId: "milestone-exam-2",
  },
];

export const MOCK_DAILY_QUESTS: DailyQuest[] = [
  {
    id: "quest-1",
    title: "Vượt qua 1 bài Quiz với điểm ≥ 80%",
    description: "Thử sức với các bài quiz theo chủ đề ngữ pháp",
    progress: 1,
    target: 1,
    rewardXp: 50,
    isCompleted: true,
  },
  {
    id: "quest-2",
    title: "Hoàn thành thử thách Viết lại câu",
    description: "Ghép đúng các thẻ từ mà không dùng từ thừa",
    progress: 0,
    target: 1,
    rewardXp: 40,
    isCompleted: false,
  },
  {
    id: "quest-3",
    title: "Duy trì chuỗi học tập 7 ngày liên tiếp",
    description: "Đăng nhập và hoàn thành ít nhất 1 bài học mỗi ngày",
    progress: 6,
    target: 7,
    rewardXp: 100,
    isCompleted: false,
  },
];

export const MOCK_QUIZZES: QuizItem[] = [
  {
    id: "ielts-academic-grammar",
    title: "IELTS Academic Core Grammar & Syntax",
    category: "Grammar Mastery",
    level: "Advanced",
    description:
      "Bài kiểm tra tổng hợp cấu trúc đảo ngữ, mệnh đề quan hệ rút gọn, liên từ và câu điều kiện thông qua 5 dạng bài tập tương tác.",
    timeLimitMinutes: 15,
    passingScorePercent: 75,
    bestScorePercent: 90,
    totalAttempts: 3,
    questions: [
      {
        id: "q-1",
        type: "MULTIPLE_CHOICE",
        title: "Câu hỏi 1: Cấu trúc Đảo ngữ thời gian",
        prompt:
          "Chọn từ thích hợp điền vào chỗ trống:\n\n'Hardly had I arrived at the international airport ______ the departure gate announced final boarding.'",
        points: 2,
        explanation:
          "Cấu trúc đảo ngữ 'Hardly had + S + V3/ed... WHEN + S + V2/ed' mang nghĩa 'Vừa mới... thì...'. Lưu ý 'No sooner' mới đi kèm với 'THAN'.",
        mcOptions: [
          { id: "opt-a", label: "A", text: "when" },
          { id: "opt-b", label: "B", text: "than" },
          { id: "opt-c", label: "C", text: "then" },
          { id: "opt-d", label: "D", text: "as soon as" },
        ],
        correctOptionId: "opt-a",
      },
      {
        id: "q-2",
        type: "FILL_BLANK",
        title: "Câu hỏi 2: Cụm động từ",
        prompt:
          "Điền giới từ thích hợp vào chỗ trống để tạo thành cụm động từ mang nghĩa 'hoãn lại' (delay / postpone):",
        points: 2,
        explanation:
          "'Put off' là phrasal verb đồng nghĩa với 'postpone' hoặc 'delay'. Ví dụ: put off the meeting = hoãn cuộc họp.",
        beforeText: "The executive committee decided to put",
        afterText: "the annual general meeting until next month due to health concerns.",
        acceptedAnswers: ["off"],
      },
      {
        id: "q-3",
        type: "REWRITE",
        title: "Câu hỏi 3: Viết lại câu với từ cho sẵn",
        prompt:
          "Viết lại câu sau sử dụng từ khoá cho sẵn, click chọn các thẻ từ theo đúng thứ tự (không dùng các từ gây nhiễu):",
        points: 2,
        originalSentence: "Although it rained heavily, they thoroughly enjoyed the outdoor music festival.",
        rewriteKeyword: "DESPITE",
        explanation:
          "'Despite + Noun Phrase' thay thế cho 'Although + Clause'. Viết lại đúng: 'Despite the heavy rain they thoroughly enjoyed the outdoor music festival'.",
        rewriteWordBank: [
          "Despite",
          "the",
          "heavy",
          "rain",
          "they",
          "thoroughly",
          "enjoyed",
          "the",
          "outdoor",
          "music",
          "festival",
          "although",
          "because",
          "raining",
          "heavily",
        ],
        correctRewriteWords: [
          "Despite",
          "the",
          "heavy",
          "rain",
          "they",
          "thoroughly",
          "enjoyed",
          "the",
          "outdoor",
          "music",
          "festival",
        ],
      },
      {
        id: "q-4",
        type: "REORDER",
        title: "Câu hỏi 4: Sắp xếp trật tự từ thành câu đúng",
        prompt:
          "Nhấp vào các khối từ bên dưới để sắp xếp thành một câu đảo ngữ hoàn chỉnh và đúng ngữ pháp:",
        points: 2,
        explanation:
          "Cấu trúc: 'No sooner + had + S + V3/ed + than + S + V2/ed' mang nghĩa ngay khi vừa làm xong việc gì thì việc khác ập đến.",
        scrambledWords: [
          "had",
          "No",
          "sooner",
          "the",
          "guests",
          "arrived",
          "than",
          "the",
          "power",
          "went",
          "out",
        ],
        correctOrderWords: [
          "No",
          "sooner",
          "had",
          "the",
          "guests",
          "arrived",
          "than",
          "the",
          "power",
          "went",
          "out",
        ],
      },
      {
        id: "q-5",
        type: "MATCHING",
        title: "Câu hỏi 5: Nối các vế câu điều kiện",
        prompt:
          "Bấm chọn một mệnh đề ở cột bên trái, sau đó bấm mệnh đề tương ứng ở cột bên phải để tạo thành câu điều kiện chuẩn xác:",
        points: 2,
        explanation:
          "- If she had studied harder -> she would have passed the exam (ĐK loại 3).\n- Unless you reserve in advance -> you will not get a table tonight (ĐK loại 1).\n- Provided that the weather is fine -> we will hold the sports festival outside (ĐK loại 1).\n- Had I known about the flight cancellation -> I would not have driven to the airport (Đảo ngữ ĐK loại 3).",
        matchingPairs: [
          {
            id: "pair-1",
            left: "If she had studied harder for the finals,",
            right: "she would have passed with flying colors.",
          },
          {
            id: "pair-2",
            left: "Unless you reserve in advance,",
            right: "you will not get a table at that bistro tonight.",
          },
          {
            id: "pair-3",
            left: "Provided that the weather remains fine,",
            right: "we will hold the sports festival outside.",
          },
          {
            id: "pair-4",
            left: "Had I known about the flight cancellation,",
            right: "I would not have driven all the way to the airport.",
          },
        ],
      },
    ],
  },
  {
    id: "business-office-collocations",
    title: "Business & Office Collocations Challenge",
    category: "Vocabulary in Context",
    level: "Intermediate",
    description:
      "Thử thách nắm bắt các cụm từ chuyên dụng trong soạn thảo email, hợp đồng và hội họp công sở.",
    timeLimitMinutes: 10,
    passingScorePercent: 70,
    bestScorePercent: 85,
    totalAttempts: 2,
    questions: [
      {
        id: "biz-1",
        type: "MULTIPLE_CHOICE",
        title: "Câu hỏi 1: Đàm phán hợp đồng",
        prompt:
          "Sau nhiều giờ thảo luận, hai công ty đã đạt được thỏa thuận chung:\n\n'Both parties finally ______ an agreement after hours of negotiation.'",
        points: 5,
        explanation: "'Reach an agreement' hoặc 'come to an agreement' là collocation chuẩn.",
        mcOptions: [
          { id: "opt-1", label: "A", text: "reached" },
          { id: "opt-2", label: "B", text: "took" },
          { id: "opt-3", label: "C", text: "made" },
          { id: "opt-4", label: "D", text: "did" },
        ],
        correctOptionId: "opt-1",
      },
      {
        id: "biz-2",
        type: "FILL_BLANK",
        title: "Câu hỏi 2: Tuân thủ quy tắc",
        prompt:
          "Điền giới từ thích hợp: 'The new policy was designed in compliance ______ international security guidelines.'",
        points: 5,
        explanation: "'In compliance with' là cụm giới từ cố định mang nghĩa tuân thủ theo quy định.",
        beforeText: "The new policy was designed in compliance",
        afterText: "international security guidelines.",
        acceptedAnswers: ["with"],
      },
    ],
  },
  {
    id: "phrasal-verbs-action",
    title: "Everyday Phrasal Verbs in Action",
    category: "Phrasal Verbs",
    level: "Beginner",
    description:
      "Ôn tập 20 cụm động từ thông dụng nhất trong giao tiếp đời thường của người bản ngữ Anh - Mỹ.",
    timeLimitMinutes: 10,
    passingScorePercent: 70,
    bestScorePercent: 90,
    totalAttempts: 4,
    questions: [
      {
        id: "pv-1",
        type: "MULTIPLE_CHOICE",
        title: "Câu hỏi 1: Tình cờ gặp gỡ",
        prompt:
          "'I ______ an old high school friend while shopping at the supermarket yesterday.'",
        points: 5,
        explanation: "'Ran into' hoặc 'bumped into' có nghĩa là tình cờ bắt gặp.",
        mcOptions: [
          { id: "pv-opt-1", label: "A", text: "ran into" },
          { id: "pv-opt-2", label: "B", text: "ran down" },
          { id: "pv-opt-3", label: "C", text: "ran over" },
          { id: "pv-opt-4", label: "D", text: "ran out" },
        ],
        correctOptionId: "pv-opt-1",
      },
      {
        id: "pv-2",
        type: "FILL_BLANK",
        title: "Câu hỏi 2: Từ bỏ thói quen",
        prompt:
          "Điền giới từ: 'He decided to give ______ smoking for the sake of his health.'",
        points: 5,
        explanation: "'Give up' nghĩa là từ bỏ một thói quen xấu.",
        beforeText: "He decided to give",
        afterText: "smoking for the sake of his health.",
        acceptedAnswers: ["up"],
      },
    ],
  },
];
