export type AuthoringKind =
  "FLASHCARD_SET" | "QUIZ" | "DICTATION_LESSON" | "SPEAKING_PROMPT" | "EXAM";
export type Metadata = {
  slug?: string;
  name?: string;
  title?: string;
  description?: string;
  topic?: string;
  category?: string;
  targetLevel?: string | null;
  timeLimitSeconds?: number;
  passingScorePercent?: number;
  referenceText?: string;
  ipaTranscript?: string;
  translationVi?: string;
  phonemeTarget?: string;
  tips?: string[];
  examType?: string;
  certificateType?: string | null;
  certificateVariant?: string | null;
  durationSeconds?: number;
  maxRawScore?: number;
  passScore?: number | null;
};
export type Option = {
  label: string;
  content: string;
  correct: boolean;
  orderNo?: number;
  explanation?: string | null;
};
export type Entry = {
  lemma?: string;
  partOfSpeech?: string;
  senseLabel?: string;
  ipaUs?: string;
  ipaUk?: string;
  audioUsObjectKey?: string | null;
  audioUkObjectKey?: string | null;
  audioUsUrl?: string;
  audioUkUrl?: string;
  definitionEn?: string;
  definitionVi?: string;
  exampleSentence?: string;
  exampleTranslationVi?: string;
  mnemonicTipVi?: string;
  cefrLevel?: string | null;
  text?: string;
  translationVi?: string;
  audioObjectKey?: string;
  audioUrl?: string;
  audioDurationSeconds?: number;
  audioStartMs?: number | null;
  audioEndMs?: number | null;
  hintFirstLetters?: string;
  hintRevealWord?: string;
  hintPartialTranscript?: string;
  questionType?: string;
  title?: string;
  prompt?: string;
  points?: number;
  explanation?: string;
  beforeText?: string;
  afterText?: string;
  originalSentence?: string;
  rewriteKeyword?: string;
  options?: Option[];
  acceptedAnswers?: string[];
  wordBank?: string[];
  correctWords?: string[];
  scrambledWords?: string[];
  correctOrder?: string[];
  pairs?: { leftText: string; rightText: string }[];
};
export type ExamQuestion = {
  questionType: string;
  content: string;
  difficultyLevel: string;
  skillType: string;
  orderNo: number;
  maxRawScore: number;
  explanation?: string | null;
  questionCategory?: string | null;
  sourceQuestionId?: string | null;
  options: Option[];
};
export type ExamSet = {
  title?: string | null;
  instruction?: string | null;
  content?: string | null;
  orderNo: number;
  audioObjectKey?: string | null;
  imageObjectKey?: string | null;
  audioUrl?: string;
  imageUrl?: string;
  sourceQuestionSetId?: string | null;
  questions: ExamQuestion[];
};
export type ExamPart = {
  title: string;
  instruction?: string | null;
  content?: string | null;
  orderNo: number;
  audioObjectKey?: string | null;
  imageObjectKey?: string | null;
  audioUrl?: string;
  imageUrl?: string;
  questionSets: ExamSet[];
};
export type ExamSection = {
  sectionType: string;
  orderNo: number;
  maxRawScore: number;
  scoredByCriteria: boolean;
  timeLimitSeconds?: number | null;
  parts: ExamPart[];
};
export type AuthoringDocument = {
  id?: string;
  version: number;
  status?: string;
  reviewNote?: string | null;
  metadata: Metadata;
  content?: { cards?: Entry[]; questions?: Entry[]; sections?: ExamSection[] };
  cards?: Entry[];
  questions?: Entry[];
  sentences?: Entry[];
  media?: Record<string, string>;
};
